apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-frontend
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tienda-frontend
  template:
    metadata:
      labels:
        app: tienda-frontend
    spec:
      # ESTO ES CRÍTICO: Si el clúster pierde acceso a ECR, usará estas credenciales
      imagePullSecrets:
      - name: regcred
      containers:
        - name: frontend
          # Cambiamos a 'latest' o dejaremos que el pipeline lo sobreescriba
          image: 542768639545.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest
          imagePullPolicy: Always  # <--- ESTO ES LO MÁS IMPORTANTE
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
